require("../node_modules/uupaa.binarypacker0x0001.js/lib/BinaryPacker0x0001.js");
require("../../WebModule/lib/Console.js");
require("../../WebModule/lib/Help.js");
require("../../WebModule/lib/Valid.js");
require("../../WebModule/lib/TestTask.js");
require("../../WebModule/lib/Test.js");
require("../lib/BinaryPacker.js");
require("../release/BinaryPacker.min.js");
require("./testcase.js");
